language: objective-c
osx_image: xcode12.5

xcode_workspace: Swindler.xcworkspace
xcode_scheme: Swindler

script:
  - swift test
  - swift build --target SwindlerExample
env:
  - SWIFT_VERSION=5.1

deploy:
  - provider: script
    script: bash .scripts/update-gh-pages.sh
    skip_cleanup: true
    on:
        all_branches: true
        condition: '"$TRAVIS_BRANCH" == "master" || "$TRAVIS_TAG" != ""'
