language: objective-c
cache: cocoapods
install: pod install || pod install --repo-update

xcode_workspace: Swindler.xcworkspace
xcode_scheme: Swindler

script: xcodebuild -workspace Swindler.xcworkspace -scheme Swindler build test
